/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#2f3445",
        "secondary-fixed-dim": "#a4c9ff",
        "on-tertiary-container": "#1c2b3c",
        "on-secondary-container": "#d6e5ff",
        "on-tertiary-fixed-variant": "#39485a",
        "on-primary": "#002e6a",
        "on-primary-fixed": "#001a42",
        "on-background": "#dee1f7",
        "surface-container-low": "#161b2b",
        "on-primary-fixed-variant": "#004395",
        "surface-tint": "#adc6ff",
        "primary-fixed-dim": "#adc6ff",
        "inverse-on-surface": "#2b3040",
        "tertiary-fixed": "#d4e4fa",
        "tertiary-fixed-dim": "#b9c8de",
        "surface-dim": "#0e1322",
        "outline-variant": "#424754",
        "inverse-primary": "#005ac2",
        "error-container": "#93000a",
        "secondary-fixed": "#d4e3ff",
        "on-tertiary": "#233143",
        "tertiary": "#b9c8de",
        "on-tertiary-fixed": "#0d1c2d",
        "tertiary-container": "#8392a6",
        "surface-container-highest": "#2f3445",
        "on-secondary": "#00315d",
        "on-primary-container": "#00285d",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "secondary": "#a4c9ff",
        "on-secondary-fixed": "#001c39",
        "on-secondary-fixed-variant": "#004883",
        "surface-bright": "#343949",
        "surface-container-lowest": "#090e1c",
        "primary-fixed": "#d8e2ff",
        "outline": "#8c909f",
        "surface-container": "#1a1f2f",
        "on-surface-variant": "#c2c6d6",
        "inverse-surface": "#dee1f7",
        "surface": "#0e1322",
        "primary": "#adc6ff",
        "surface-container-high": "#25293a",
        "primary-container": "#4d8eff",
        "background": "#0e1322",
        "secondary-container": "#0267b8",
        "on-surface": "#dee1f7"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}

